<?php
return [
    'Connexion'=>'Inicio de sesión','Inscription'=>'Registro','Langue'=>'Idioma','Élève'=>'Estudiante','Enseignant'=>'Docente','Code élève'=>'Código de estudiante','Identifiant'=>'Usuario','Mot de passe'=>'Contraseña','Se connecter'=>'Iniciar sesión','S’inscrire'=>'Registrarse','Pas encore de compte ?'=>'¿Aún no tienes cuenta?',
    'Didactique et pédagogie'=>'Didáctica y pedagogía','Chemins différenciés, mais vision commune.'=>'Caminos diferentes, una visión común.',"Retrouvez les étapes du parcours d'apprentissage, acquis et encouragements, en un seul et même endroit, disponible 24/7."=>'Etapas de aprendizaje, logros y ánimos en un solo lugar, disponible 24/7.',
    'Ton code personnel'=>'Tu código personal','2 premières lettres du prénom + 3 premières du nom.'=>'Primeras 2 letras del nombre + primeras 3 del apellido.','Espace enseignant'=>'Espacio docente','Connectez-vous pour gérer les élèves, contenus et parcours.'=>'Inicia sesión para gestionar estudiantes, contenidos e itinerarios.','Ex. nora'=>'Ej. nora','Ex. LIROS'=>'Ej. LIROS',
    'Bienvenue'=>'Bienvenido','Créer son espace.'=>'Crea tu cuenta.','Retour à la connexion'=>'Volver al inicio','Créer un compte enseignant'=>'Crear una cuenta docente','Créer un compte élève'=>'Crear una cuenta de estudiante','Votre premier cours sera créé avec votre compte.'=>'Tu primer curso se creará con tu cuenta.','Votre enseignant pourra ensuite vous inscrire à ses cours.'=>'Tu docente podrá inscribirte después en sus cursos.','Le compte ne sera actif qu’après validation du courriel dans les 15 minutes.'=>'La cuenta solo se activará tras confirmar el correo en un plazo de 15 minutos.',
    'Prénom'=>'Nombre','NOM'=>'APELLIDO','Nom'=>'Apellido','Courriel'=>'Correo electrónico','Téléphone'=>'Teléfono','facultatif'=>'opcional','Identifiant souhaité'=>'Usuario deseado','Premier cours'=>'Primer curso','Confirmation'=>'Confirmación','Groupe classe'=>'Grupo de clase','Créer mon compte'=>'Crear mi cuenta','Code personnel proposé'=>'Código personal propuesto','Un chiffre sera ajouté automatiquement si ce code existe déjà.'=>'Si el código ya existe, se añadirá un número automáticamente.',
    'Suivi'=>'Seguimiento','Élèves'=>'Estudiantes','Bibliothèque'=>'Biblioteca','Parcours'=>'Itinerarios','Aujourd’hui'=>'Hoy','Acquis'=>'Logros','Encouragements'=>'Recompensas','Connecté·e comme'=>'Sesión iniciada como','Modifier mon profil'=>'Editar mi perfil','Superadministration'=>'Superadministración','Se déconnecter'=>'Cerrar sesión',
    'Mon profil'=>'Mi perfil','Compte enseignant'=>'Cuenta docente','Compte élève'=>'Cuenta de estudiante','Langue de l’interface'=>'Idioma de la interfaz','Enregistrer mon profil'=>'Guardar mi perfil','Aperçu'=>'Vista previa','Changer le mot de passe'=>'Cambiar contraseña','Nouveau mot de passe'=>'Nueva contraseña','Votre profil a été mis à jour.'=>'Tu perfil se ha actualizado.','Bienvenue :name !'=>'¡Bienvenido, :name!','Identifiant ou mot de passe incorrect.'=>'Usuario o contraseña incorrectos.','Code élève inconnu.'=>'Código de estudiante desconocido.','Formulaire expiré. Rechargez la page.'=>'El formulario ha caducado. Recarga la página.',
    ':count page(s)'=>':count página(s)','Écraser cette page et remplacer tous ses blocs et tags ?'=>'¿Sobrescribir esta página y reemplazar todos sus bloques y etiquetas?','Écraser ce parcours ? Ses anciennes étapes, progressions et encouragements liés seront supprimés.'=>'¿Sobrescribir este itinerario? Se eliminarán sus etapas anteriores, progresos y recompensas relacionadas.','Écraser, pour les élèves importés, leurs inscriptions à vos parcours ?'=>'¿Sobrescribir las inscripciones a tus itinerarios para los estudiantes importados?',
];
