<?php
return [
    'Connexion'=>'Accesso','Inscription'=>'Registrazione','Langue'=>'Lingua','Élève'=>'Studente','Enseignant'=>'Docente','Code élève'=>'Codice studente','Identifiant'=>'Nome utente','Mot de passe'=>'Password','Se connecter'=>'Accedi','S’inscrire'=>'Registrati','Pas encore de compte ?'=>'Non hai ancora un account?',
    'Didactique et pédagogie'=>'Didattica e pedagogia','Chemins différenciés, mais vision commune.'=>'Percorsi differenziati, una visione comune.',"Retrouvez les étapes du parcours d'apprentissage, acquis et encouragements, en un seul et même endroit, disponible 24/7."=>'Tappe di apprendimento, risultati e incoraggiamenti in un unico posto, disponibile 24/7.',
    'Ton code personnel'=>'Il tuo codice personale','2 premières lettres du prénom + 3 premières du nom.'=>'Prime 2 lettere del nome + prime 3 del cognome.','Espace enseignant'=>'Area docenti','Connectez-vous pour gérer les élèves, contenus et parcours.'=>'Accedi per gestire studenti, contenuti e percorsi.','Ex. nora'=>'Es. nora','Ex. LIROS'=>'Es. LIROS',
    'Bienvenue'=>'Benvenuto','Créer son espace.'=>'Crea il tuo account.','Retour à la connexion'=>'Torna all’accesso','Créer un compte enseignant'=>'Crea un account docente','Créer un compte élève'=>'Crea un account studente','Votre premier cours sera créé avec votre compte.'=>'Il primo corso verrà creato con il tuo account.','Votre enseignant pourra ensuite vous inscrire à ses cours.'=>'Il docente potrà poi iscriverti ai suoi corsi.','Le compte ne sera actif qu’après validation du courriel dans les 15 minutes.'=>'L’account sarà attivo solo dopo la conferma dell’email entro 15 minuti.',
    'Prénom'=>'Nome','NOM'=>'COGNOME','Nom'=>'Cognome','Courriel'=>'Email','Téléphone'=>'Telefono','facultatif'=>'facoltativo','Identifiant souhaité'=>'Nome utente desiderato','Premier cours'=>'Primo corso','Confirmation'=>'Conferma','Groupe classe'=>'Classe','Créer mon compte'=>'Crea il mio account','Code personnel proposé'=>'Codice personale proposto','Un chiffre sera ajouté automatiquement si ce code existe déjà.'=>'Se il codice esiste già, verrà aggiunto automaticamente un numero.',
    'Suivi'=>'Monitoraggio','Élèves'=>'Studenti','Bibliothèque'=>'Biblioteca','Parcours'=>'Percorsi','Aujourd’hui'=>'Oggi','Acquis'=>'Competenze','Encouragements'=>'Ricompense','Connecté·e comme'=>'Accesso come','Modifier mon profil'=>'Modifica il profilo','Superadministration'=>'Superamministrazione','Se déconnecter'=>'Esci',
    'Mon profil'=>'Il mio profilo','Compte enseignant'=>'Account docente','Compte élève'=>'Account studente','Langue de l’interface'=>'Lingua dell’interfaccia','Enregistrer mon profil'=>'Salva il profilo','Aperçu'=>'Anteprima','Changer le mot de passe'=>'Cambia password','Nouveau mot de passe'=>'Nuova password','Votre profil a été mis à jour.'=>'Il profilo è stato aggiornato.','Bienvenue :name !'=>'Benvenuto :name!','Identifiant ou mot de passe incorrect.'=>'Nome utente o password errati.','Code élève inconnu.'=>'Codice studente sconosciuto.','Formulaire expiré. Rechargez la page.'=>'Modulo scaduto. Ricarica la pagina.',
    ':count page(s)'=>':count pagina/e','Écraser cette page et remplacer tous ses blocs et tags ?'=>'Sovrascrivere questa pagina e sostituire tutti i blocchi e tag?','Écraser ce parcours ? Ses anciennes étapes, progressions et encouragements liés seront supprimés.'=>'Sovrascrivere questo percorso? Le tappe precedenti, i progressi e le ricompense collegate verranno eliminati.','Écraser, pour les élèves importés, leurs inscriptions à vos parcours ?'=>'Sovrascrivere le iscrizioni ai tuoi percorsi per gli studenti importati?',
];
