<?php
declare(strict_types=1);
function messaging_body_html(string $body): string
{
    $parts=preg_split('~(https?://[^\s<>]+)~u',$body,-1,PREG_SPLIT_DELIM_CAPTURE);$html='';
    foreach($parts as $i=>$part)$html.=$i%2?'<a href="'.e($part).'" target="_blank" rel="noopener noreferrer">'.e($part).'</a>':nl2br(e($part));return $html;
}
function messaging_people_to_manage(array $user): array
{
    if($user['role']!=='teacher')return [];
    $store=messaging_store();$result=[];
    foreach($store->query('SELECT DISTINCT user_key,name FROM participants ORDER BY name') as $p){if(messaging_super($user)||messaging_threads($user,$p['user_key']))$result[$p['user_key']]=$p['name'];}return $result;
}
function messaging_erase_version(array $ids): string
{
    return messaging_store()->eraseVersion($ids);
}
function view_discussions(): void
{
    $user=require_actor();$key=messaging_key($user);$person=trim((string)($_GET['person']??''));$managed=$person!=='';
    $people=messaging_people_to_manage($user);
    if($managed&&!isset($people[$person])){echo '<p class="empty">'.e(t('Aucune discussion accessible.')).'</p>';return;}
    $threads=messaging_threads($user,$managed?$person:null);$selected=(string)($_GET['thread']??'');$thread=null;
    if($selected!==''){try{$thread=messaging_thread($user,$selected,false,$managed);}catch(Throwable){echo '<p class="empty">'.e(t('Accès interdit.')).'</p>';return;}}
    if(!$selected&&$threads){$thread=$threads[0];$selected=$thread['id'];}
    $canWrite=$thread&&!$managed&&messaging_authorize($user,$thread,true);$canExport=$thread&&messaging_authorize($user,$thread,false,true);
    ?><section class="teacher-heading chat-heading"><div><h1><?=e(t('Discussions'))?></h1></div><div class="dropdown chat-actions-menu"><button class="btn btn-light pathway-actions-toggle chat-actions-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" aria-label="<?=e(t('Actions'))?>" title="<?=e(t('Actions'))?>"><i class="bi bi-three-dots-vertical" aria-hidden="true"></i></button><div class="dropdown-menu dropdown-menu-end chat-actions"><button type="button" class="dropdown-item btn btn-outline-secondary" data-enable-push><i class="bi bi-bell" data-push-icon aria-hidden="true"></i><span data-push-label><?=e(t('Activer les notifications'))?></span></button><?php if(!$managed): ?><button type="button" class="dropdown-item btn btn-primary" data-bs-toggle="modal" data-bs-target="#new-discussion"><i class="bi bi-chat-left-dots" aria-hidden="true"></i><span><?=e(t('Nouvelle discussion'))?></span></button><?php endif; ?></div></div></section><p data-push-feedback role="status"></p>
    <?php if($people): ?><details class="chat-management" <?=$managed?'open':''?>><summary><i class="bi bi-chevron-right" aria-hidden="true"></i><span><?=e(t(messaging_super($user)?'Gérer toutes les discussions':'Gérer les discussions de mes parcours'))?></span></summary><form method="get" class="d-flex gap-2 mt-3"><input type="hidden" name="view" value="discussions"><select name="person" aria-label="<?=e(t('Personne'))?>"><?php foreach($people as $id=>$name): ?><option value="<?=e($id)?>" <?=$person===$id?'selected':''?>><?=e($name)?></option><?php endforeach; ?></select><button class="btn btn-outline-primary"><?=e(t('Consulter'))?></button></form>
    <?php foreach(messaging_requests($user) as $request): ?><p class="mt-2"><a href="<?=e(route('discussions',['person'=>$request['user_key']]))?>"><?=e($request['name'])?></a> · <?=e(t('Demande d’effacement'))?> · <?=e(messaging_timestamp((int)$request['requested_at']))?></p><?php endforeach; ?></details><?php endif; ?>
    <?php if($managed): $ids=array_column($threads,'id');$total=array_sum(array_column($threads,'count')); ?><section class="chat-management"><h2><?=e($people[$person])?></h2><p><?=e(t(':threads fils et :messages messages accessibles.',['threads'=>count($ids),'messages'=>$total]))?></p><div class="d-flex flex-wrap gap-2"><?php foreach(['pdf'=>'PDF','markdown'=>'Markdown','json'=>'JSON'] as $format=>$label): ?><a class="btn btn-outline-secondary" href="<?=e(route('discussion-export',['person'=>$person,'format'=>$format]))?>"><?=e(t('Exporter'))?> <?=$label?></a><?php endforeach; ?><form method="post" data-chat-erase data-confirm="<?=e(t('Effacer définitivement les :threads fils et :messages messages affichés, pour tous leurs participants ?',['threads'=>count($ids),'messages'=>$total]))?>"><?=csrf_field()?><input type="hidden" name="action" value="messaging_erase"><input type="hidden" name="person" value="<?=e($person)?>"><input type="hidden" name="erase_version" value="<?=e(messaging_erase_version($ids))?>"><?php foreach($ids as $id): ?><input type="hidden" name="threads[]" value="<?=e($id)?>"><?php endforeach; ?><button class="btn btn-outline-danger"><?=e(t('Effacer les discussions affichées'))?></button></form></div><a class="d-inline-block mt-2" href="<?=route('discussions')?>"><?=e(t('Mes discussions'))?></a></section><?php endif; ?>
    <div class="chat-layout <?=$selected?'has-thread':''?>" data-chat-root data-thread="<?=e($selected)?>" data-managed="<?=$managed?'1':'0'?>" data-person="<?=e($person)?>" data-user-key="<?=e($key)?>"><aside class="chat-list" aria-label="<?=e(t('Discussions'))?>">
    <?php foreach($threads as $row): ?><a class="chat-preview <?=$selected===$row['id']?'active':''?>" href="<?=e(route('discussions',array_filter(['thread'=>$row['id'],'person'=>$person])))?>"><strong><?=e(implode(' / ',array_column(array_filter($row['participants'],fn($p)=>$managed||$p['user_key']!==$key),'name')))?></strong><small><?=e($row['scope_title'])?></small><span><?=e($row['last']['body']??t('Aucun message.'))?></span><?php if(!$managed&&$row['unread']): ?><b class="chat-count"><?=$row['unread']?></b><?php endif; ?></a><?php endforeach; ?>
    <?php if(!$threads): ?><p class="empty"><?=e(t('Aucune discussion.'))?></p><?php endif; ?></aside><section class="chat-thread">
    <?php if($thread): ?><header><button class="btn btn-light chat-back" type="button" data-chat-back aria-label="<?=e(t('Discussions'))?>" title="<?=e(t('Discussions'))?>"><i class="bi bi-arrow-bar-left" aria-hidden="true"></i></button><div><h2><?=e(implode(' / ',array_column(array_filter($thread['participants'],fn($p)=>$managed||$p['user_key']!==$key),'name')))?></h2><p><?=e($thread['scope_title'])?></p></div><?php if($canExport): ?><div class="dropdown"><button class="btn btn-light" data-bs-toggle="dropdown" aria-label="<?=e(t('Exporter'))?>"><i class="bi bi-three-dots-vertical"></i></button><ul class="dropdown-menu dropdown-menu-end"><?php foreach(['pdf'=>'PDF','markdown'=>'Markdown','json'=>'JSON'] as $format=>$label): ?><li><a class="dropdown-item" href="<?=e(route('discussion-export',['thread'=>$selected,'format'=>$format]))?>"><?=e(t('Exporter'))?> <?=$label?></a></li><?php endforeach; ?></ul></div><?php endif; ?></header><button class="btn btn-light" type="button" data-chat-older hidden><?=e(t('Messages précédents'))?></button><div class="chat-messages" data-chat-messages aria-live="polite"></div><p class="chat-feedback" data-chat-feedback role="status"></p>
    <?php if($canWrite): ?><form method="post" class="chat-compose" data-chat-compose><?=csrf_field()?><input type="hidden" name="action" value="messaging_send"><input type="hidden" name="thread" value="<?=e($selected)?>"><input type="hidden" name="request_key" value="<?=bin2hex(random_bytes(20))?>"><label class="visually-hidden" for="chat-body"><?=e(t('Votre message'))?></label><textarea id="chat-body" name="body" rows="1" required data-chat-body placeholder="<?=e(t('Votre message'))?>"></textarea><div><small data-chat-counter hidden>0 / 256</small><button type="button" class="btn btn-light" data-chat-cancel-edit hidden aria-label="<?=e(t('Annuler'))?>" title="<?=e(t('Annuler'))?>"><i class="bi bi-x-lg" aria-hidden="true"></i></button><button class="btn btn-primary" data-chat-submit aria-label="<?=e(t('Envoyer'))?>" title="<?=e(t('Envoyer'))?>"><i class="bi bi-send-fill" aria-hidden="true"></i></button></div></form><?php else: ?><p class="empty"><?=e(t('Cette discussion est en lecture seule.'))?></p><?php endif; ?>
    <?php else: ?><p class="empty"><?=e(t('Sélectionnez une discussion ou commencez un nouvel échange.'))?></p><?php endif; ?></section></div>
    <?php if(!$managed): ?><details class="chat-management chat-deletion-request"><summary><i class="bi bi-chevron-right" aria-hidden="true"></i><span><?=e(t('Demander l’effacement de toutes mes discussions'))?></span></summary><p><?=e(t('La demande sera transmise aux responsables de vos parcours et au superadmin. L’effacement concerne les fils complets, pour tous leurs participants.'))?></p><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="messaging_request_delete"><button class="btn btn-outline-danger"><?=e(t('Envoyer la demande'))?></button></form><?php if(messaging_store()->query("SELECT 1 FROM deletion_requests WHERE user_key=? AND status='pending'",[$key])): ?><p><?=e(t('Votre demande est en attente.'))?></p><?php endif; ?></details><?php endif; ?>
    <?php messaging_new_dialog($user); ?>
    <script type="application/json" id="chat-i18n"><?=json_encode(array_combine(['edit','edited','send','save','error','disabled','confirm','permission','length','enableNotifications','disableNotifications','notificationsOff'],array_map('t',['Modifier','Modifié','Envoyer','Enregistrer','Impossible de terminer cette opération. Réessayez.','Cette discussion est en lecture seule.','Confirmer','Les notifications ne sont pas autorisées sur cet appareil.','256 caractères maximum.','Activer les notifications','Désactiver les notifications','Notifications désactivées sur cet appareil.'])),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE)?></script><?php
}
function messaging_new_dialog(array $user): void
{
    $courses=$user['role']==='student'?all("SELECT c.* FROM courses c JOIN enrollments e ON e.course_id=c.id WHERE e.student_id=? AND e.status='active' AND c.messaging_enabled=1 AND c.archived=0",[$user['id']]):all("SELECT c.* FROM courses c WHERE c.messaging_enabled=1 AND c.archived=0 AND (c.teacher_id=? OR EXISTS(SELECT 1 FROM course_teachers ct WHERE ct.course_id=c.id AND ct.teacher_id=?))",[$user['id'],$user['id']]);
    $recipients=[];foreach($courses as $course){$rows=$user['role']==='student'?all("SELECT u.id,u.name FROM users u WHERE u.account_status='active' AND (u.id=? OR EXISTS(SELECT 1 FROM course_teachers ct WHERE ct.teacher_id=u.id AND ct.course_id=?))",[$course['teacher_id'],$course['id']]):all("SELECT u.id,u.name FROM users u JOIN enrollments e ON e.student_id=u.id WHERE e.course_id=? AND e.status='active' AND u.account_status='active'",[$course['id']]);foreach($rows as $r){$recipients[$r['id']]['name']=$r['name'];$recipients[$r['id']]['courses'][]=(int)$course['id'];}}
    ?><div class="modal fade" id="new-discussion" tabindex="-1" aria-labelledby="new-discussion-title"><div class="modal-dialog"><div class="modal-content"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="messaging_open"><div class="modal-header"><h2 class="modal-title fs-5" id="new-discussion-title"><?=e(t('Nouvelle discussion'))?></h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?=e(t('Fermer'))?>"></button></div><div class="modal-body"><label class="field"><span><?=e(t('Parcours'))?></span><select name="course_id" required data-chat-course><?php foreach($courses as $c): ?><option value="<?=$c['id']?>" <?=(int)($_GET['course']??0)===(int)$c['id']?'selected':''?>><?=e($c['title'])?></option><?php endforeach; ?></select></label><label class="field"><span><?=e(t('Destinataire'))?></span><select name="recipient_id" required data-chat-recipient><?php foreach($recipients as $id=>$r): ?><option value="<?=$id?>" data-courses="<?=e(json_encode($r['courses']))?>"><?=e($r['name'])?></option><?php endforeach; ?></select></label><?php if(!$courses): ?><p><?=e(t('Aucun parcours ne permet de commencer une discussion.'))?></p><?php endif; ?></div><div class="modal-footer"><button class="btn btn-primary" <?=$courses?'':'disabled'?>><?=e(t('Ouvrir la discussion'))?></button></div></form></div></div></div><?php
}
