<?php

declare(strict_types=1);

function render_message_variables(): void
{
    ?><div class="message-variables"><span><?=e(t('Insérer'))?></span><?php foreach(AnnouncementMessages::VARIABLES as $variable): ?><button type="button" class="btn btn-sm btn-outline-secondary" data-message-variable="<?=e($variable)?>"><?=e('{'.$variable.'}')?></button><?php endforeach; ?></div><?php
}

function render_teacher_message_actions(array $course,array $students): void
{
    $templates=AnnouncementMessages::templates(db(),(int)actor()['id']);
    $actions=['send'=>t('Courriel / Annonce'),'templates'=>t('Créer / modifier les modèles')];
    foreach(StudentAdminHistory::KINDS as $kind=>$label)$actions['followup-'.$kind]=t($label);
    uasort($actions,'pathway_natural_compare');
    $messages=['sender'=>(string)actor()['email'],'open'=>t('Voir l’annonce'),'select'=>t('Choisir un modèle'),'new'=>t('Nouveau modèle'),'preview'=>t('Aperçu'),'send'=>t('Envoyer à :count élèves'),'count'=>t(':count élèves · :copies copies CC · CCI à :email'),'saved'=>t('Modèle enregistré.'),'deleted'=>t('Modèle supprimé.'),'deleteConfirm'=>t('Supprimer ce modèle ? Les messages déjà envoyés seront conservés.'),'error'=>t('L’opération a échoué. Votre saisie est conservée.'),'sent'=>t('Annonce publiée et courriels préparés.'),'waiting'=>t('En cours…')];
    ?><div class="teacher-message-actions" data-message-tools data-message-templates="<?=e(json_encode($templates,JSON_UNESCAPED_UNICODE))?>" data-message-labels="<?=e(json_encode($messages,JSON_UNESCAPED_UNICODE))?>"><label class="field"><span><?=e(t('Actions'))?></span><select data-message-action><option value=""><?=e(t('Choisir une action'))?></option><?php foreach($actions as $value=>$label): ?><option value="<?=e($value)?>"><?=e($label)?></option><?php endforeach; ?></select></label><p data-message-result role="status" hidden></p></div>
    <div class="modal fade" id="teacher-message-modal" tabindex="-1" aria-labelledby="teacher-message-title" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><form method="post" data-message-compose><?=csrf_field()?><input type="hidden" name="course_id" value="<?=(int)$course['id']?>"><input type="hidden" name="request_key" value="<?=e(bin2hex(random_bytes(24)))?>">
      <div class="modal-header"><h2 class="modal-title fs-5" id="teacher-message-title"><?=e(t('Envoyer un message'))?></h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?=e(t('Fermer'))?>"></button></div>
      <div class="modal-body"><div class="message-composer-grid"><section><h3><?=e(t('Destinataires'))?></h3><div class="message-select-all"><label><input type="checkbox" data-message-all> <?=e(t('Toute la classe'))?></label><label><input type="checkbox" data-message-all-cc> <?=e(t('Inclure les 2es adresses disponibles (CC)'))?></label></div><div class="message-recipient-list"><?php foreach($students as $student): $secondary=trim((string)($student['secondary_email']??'')); ?><div class="message-recipient-row"><label><input type="checkbox" name="students[]" value="<?=(int)$student['id']?>"><span><b><?=e($student['name'])?></b><small><?=e($student['email'])?></small></span></label><?php if($secondary!==''): ?><label class="message-recipient-cc"><input type="checkbox" name="secondary[]" value="<?=(int)$student['id']?>" disabled><span><b>CC</b> <?=e($secondary)?></span></label><?php endif; ?></div><?php endforeach; ?></div></section>
      <section><label class="field"><span><?=e(t('Modèle'))?></span><select name="template_id" data-message-template><option value="0"><?=e(t('Choisir un modèle'))?></option><?php foreach($templates as $template): ?><option value="<?=(int)$template['id']?>"><?=e($template['name'])?></option><?php endforeach; ?></select></label><label class="field"><span><?=e(t('Titre'))?></span><input name="title" required maxlength="160"></label><label class="field"><span><?=e(t('Message en Markdown'))?></span><textarea name="body" required maxlength="5000" rows="8"></textarea></label><?php render_message_variables(); ?><small class="muted-copy"><?=e(t('Aucun prénom ni signature ajoutés automatiquement.'))?></small><p class="message-copy-note"><?=e(t('Votre adresse sera ajoutée en CCI à chaque courriel.'))?></p><button type="button" class="btn btn-sm btn-outline-secondary" data-message-save-as-template><?=e(t('Enregistrer comme modèle'))?></button></section></div>
      <p data-message-count class="message-count"></p><p data-message-feedback role="status" hidden></p><section data-message-preview hidden><h3><?=e(t('Aperçu personnalisé'))?></h3><label class="field"><span><?=e(t('Élève'))?></span><select data-message-preview-student></select></label><p data-message-preview-addresses></p><h4 data-message-preview-title></h4><div class="content-block" data-message-preview-body></div></section></div>
      <div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal"><?=e(t('Fermer'))?></button><button type="button" class="btn btn-outline-primary" data-message-preview-button><?=e(t('Aperçu'))?></button><button type="submit" class="btn btn-primary" data-message-send disabled><?=e(t('Envoyer'))?></button></div>
    </form></div></div></div>
    <div class="modal fade" id="message-template-modal" tabindex="-1" aria-labelledby="message-template-title" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><form method="post" data-message-template-form><?=csrf_field()?><input type="hidden" name="revision" value="0"><div class="modal-header"><h2 class="modal-title fs-5" id="message-template-title"><?=e(t('Créer / modifier les modèles'))?></h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?=e(t('Fermer'))?>"></button></div><div class="modal-body"><p><?=e(t('Vos modèles sont disponibles dans tous vos parcours.'))?></p><label class="field"><span><?=e(t('Modèle'))?></span><select name="template_id" data-message-template-manager><option value="0"><?=e(t('Nouveau modèle'))?></option><?php foreach($templates as $template): ?><option value="<?=(int)$template['id']?>"><?=e($template['name'])?></option><?php endforeach; ?></select></label><label class="field"><span><?=e(t('Nom du modèle'))?></span><input name="name" maxlength="100" required></label><label class="field"><span><?=e(t('Titre'))?></span><input name="title" maxlength="160" required></label><label class="field"><span><?=e(t('Message en Markdown'))?></span><textarea name="body" rows="8" maxlength="5000" required></textarea></label><?php render_message_variables(); ?><p data-template-feedback role="status" hidden></p></div><div class="modal-footer"><button type="button" class="btn btn-outline-danger" data-template-delete disabled><?=e(t('Supprimer'))?></button><button type="button" class="btn btn-light" data-bs-dismiss="modal"><?=e(t('Fermer'))?></button><button class="btn btn-primary"><?=e(t('Enregistrer'))?></button></div></form></div></div></div><?php
}

function render_announcement_recipient_details(array $announcement): void
{
    if(($announcement['audience']??'all')==='all')return;
    $recipients=all('SELECT ar.*,r.read_at FROM announcement_recipients ar LEFT JOIN announcement_reads r ON r.announcement_id=ar.announcement_id AND r.student_id=ar.student_id WHERE ar.announcement_id=? ORDER BY ar.student_name',[(int)$announcement['id']]);
    ?><details class="announcement-recipients"><summary><?=e(t('Destinataires : :count élèves',['count'=>count($recipients)]))?></summary><?php foreach($recipients as $recipient): ?><details><summary><?=e($recipient['student_name'])?> · <?=e(t($recipient['read_at']?'Lu dans l’application':'Non lu dans l’application'))?></summary><small><?=e($recipient['email'])?><?=$recipient['cc']!==''?' · CC : '.e($recipient['cc']):''?></small><b><?=e($recipient['title'])?></b><div class="announcement-body"><?=Markdown::render($recipient['body'])?></div></details><?php endforeach; ?></details><?php
}
